# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('caralibroapp', '0004_auto_20160822_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caralibroapp.User')),
            ],
            managers=[
                ('PokeManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
