# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caralibroapp', '0005_poke'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poke',
            managers=[
            ],
        ),
    ]
