# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caralibroapp', '0006_auto_20160822_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='pokes',
            new_name='pokee',
        ),
        migrations.RenameField(
            model_name='poke',
            old_name='user_id',
            new_name='poker',
        ),
    ]
