# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
