# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0002_auto_20160821_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='date',
            field=models.DateField(),
        ),
    ]
