# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0003_auto_20160821_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
