# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0004_appt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
